server.port=8081
spring.application.name=modulo1-practica-dev

spring.datasource.url=jdbc:postgresql://localhost:5432/mi_basedatos
spring.datasource.username=postgres
spring.datasource.password=postgres
